print("Program Penampil Data Diri")
print("********************************")
nama = input("Masukkan Nama : ")
usia = input("Masukkan Usia Anda : ")
asal = input("Masukkan Asal Kota Anda : ")
print("Hallo nama saya", nama,"!!!", "Usia saya", usia, "saya berasal dari", asal)